export { ReactComponent as PlayIcon } from './play_arrow.svg'
export { ReactComponent as PauseIcon } from './pause.svg'
export { ReactComponent as VolumeIcon } from './volume_up.svg'
export { ReactComponent as MuteIcon } from './volume_off.svg'

export { ReactComponent as AudioDefaultIcon } from './audio_file.svg'
export { ReactComponent as OceanIcon } from './water.svg'
export { ReactComponent as RainIcon } from './rainy.svg'
export { ReactComponent as WhiteNoiseIcon } from './tv.svg'
export { ReactComponent as BirdIcon } from './bird.svg'
export { ReactComponent as KeyboardIcon } from './keyboard.svg'
export { ReactComponent as FirePlaceIcon } from './fireplace.svg'
export { ReactComponent as NightIcon } from './bedtime.svg'
export { ReactComponent as CafeIcon } from './local_cafe.svg'
export { ReactComponent as WindIcon } from './air.svg'
